name: Automated UI tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - smoke_tests_in_chrome
          - smoke_tests_in_firefox
          - all_tests_in_chrome
          - all_tests_in_firefox

jobs:
    tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python version: "3.10"
        - name: Install Chrome
          run: sudo apt-get install google-chrome-stable
        - name: Install dependensies
          run: pip install -r requirements.txt
        - name: smoke_tests_in_chrome
          if: "github.event.inputs.deployment_target == 'smoke_tests_in_chrome'"
          run: pytest -s -v -m smoke
        - name: smoke_tests_in_firefox
          if: "github.event.inputs.deployment_target == 'smoke_tests_in_firefox'"
          run: pytest -s -v -m smoke --browser_name=firefox
        - name: all_tests_in_chrome
          if: "github.event.inputs.deployment_target == 'all_tests_in_chrome'"
          run: pytest -s -v
        - name: all_tests_in_firefox
          if: "github.event.inputs.deployment_target == 'all_tests_in_chrome'"
          run: pytest -s -v --browser_name=firefox