name: Automated UI tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - run_smoke_tests_in_chrome
          - run_smoke_tests_in_firefox
          - run_all_tests_in_chrome
          - run_all_tests_in_firefox

jobs:
    tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python version: "3.10"
        - name: Install Chrome
          run: sudo apt-get install google-chrome-stable
        - name: Install dependensies
          run: pip install -r requirements.txt
        - name: run_smoke_tests_in_chrome
          if: "github.event.inputs.deployment_target == 'run_smoke_tests_in_chrome_ru'" is True
          run: pytest -sv -m smoke
        - name: run_smoke_tests_in_firefox
          if: "github.event.inputs.deployment_target == 'run_smoke_tests_in_firefox_en'" is True
          run: pytest -sv -m smoke --browser_name=firefox
        - name: run_all_tests_in_chrome
          if: "github.event.inputs.deployment_target == 'run_all_tests_in_chrome_es'" is True
          run: pytest -sv
        - name: run_all_tests_in_firefox
          if: "github.event.inputs.deployment_target == 'run_all_tests_in_chrome_es'" is True
          run: pytest -sv --browser_name=firefox